# Site settings
title: SHANITH K K
description: Resume
# baseurl: "https://github.com/shanithkk/shanithkk" # the subpath of your site, e.g. /blog
# url: "https://github.com/shanithkk/shanithkk" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: shanithkk
user_description: I'm a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. To work in a well-established organization where I can use my academic and professional education & experience, which will help in the growth and development of the organization.
user_title: Software Engineer
email: kkshanith@gmail.com
# twitter_username: shanith_kk
# github_username:  shanithkk
# gplus_username:  shanithkk

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
